
import fs from 'fs';

const wordsRaw = [
    ["ability", "能力", "n.", "əˈbɪləti"],
    ["able", "能够", "adj.", "ˈeɪbl"],
    ["about", "关于", "prep.", "əˈbaʊt"],
    ["above", "在...上面", "prep.", "əˈbʌv"],
    ["abroad", "到国外", "adv.", "əˈbrɔːd"],
    ["absent", "缺席的", "adj.", "ˈæbsənt"],
    ["absolute", "绝对的", "adj.", "ˈæbsəluːt"],
    ["absorb", "吸收", "v.", "əbˈzɔːrb"],
    ["abstract", "抽象的", "adj.", "ˈæbstrækt"],
    ["abundant", "丰富的", "adj.", "əˈbʌndənt"],
    ["academic", "学术的", "adj.", "ˌækəˈdemɪk"],
    ["academy", "学院", "n.", "əˈkædəmi"],
    ["accelerate", "加速", "v.", "əkˈseləreɪt"],
    ["accent", "口音", "n.", "ˈæksent"],
    ["accept", "接受", "v.", "əkˈsept"],
    ["access", "进入，通道", "n.", "ˈækses"],
    ["accessible", "易接近的", "adj.", "əkˈsesəbl"],
    ["accident", "事故", "n.", "ˈæksɪdənt"],
    ["accidental", "偶然的", "adj.", "ˌæksɪˈdentl"],
    ["accommodate", "容纳，适应", "v.", "əˈkɒmədeɪt"],
    ["accommodation", "住宿", "n.", "əˌkɒməˈdeɪʃn"],
    ["accompany", "陪伴", "v.", "əˈkʌmpəni"],
    ["accomplish", "完成", "v.", "əˈkʌmplɪʃ"],
    ["accord", "一致", "n./v.", "əˈkɔːrd"],
    ["accordance", "一致，和谐", "n.", "əˈkɔːrdəns"],
    ["accordingly", "因此，相应地", "adv.", "əˈkɔːrdɪŋli"],
    ["account", "账户，解释", "n.", "əˈkaʊnt"],
    ["accountant", "会计师", "n.", "əˈkaʊntənt"],
    ["accumulate", "积累", "v.", "əˈkjuːmjəleɪt"],
    ["accuracy", "准确性", "n.", "ˈækjərəsi"],
    ["accurate", "精确的", "adj.", "ˈækjərət"],
    ["accuse", "指控", "v.", "əˈkjuːz"],
    ["accustomed", "习惯的", "adj.", "əˈkʌstəmd"],
    ["ache", "疼痛", "n./v.", "eɪk"],
    ["achieve", "实现", "v.", "əˈtʃiːv"],
    ["acid", "酸的", "adj./n.", "ˈæsɪd"],
    ["acknowledge", "承认", "v.", "əkˈnɒlɪdʒ"],
    ["acquaint", "使熟悉", "v.", "əˈkweɪnt"],
    ["acquaintance", "熟人", "n.", "əˈkweɪntəns"],
    ["acquire", "获得", "v.", "əˈkwaɪər"],
    ["acquisition", "获得，收购", "n.", "ˌækwɪˈzɪʃn"],
    ["acre", "英亩", "n.", "ˈeɪkər"],
    ["act", "行动，表演", "v./n.", "ækt"],
    ["action", "行动", "n.", "ˈækʃn"],
    ["activate", "激活", "v.", "ˈæktɪveɪt"],
    ["active", "活跃的", "adj.", "ˈæktɪv"],
    ["activity", "活动", "n.", "ækˈtɪvəti"],
    ["actor", "男演员", "n.", "ˈæktər"],
    ["actress", "女演员", "n.", "ˈæktrəs"],
    ["actual", "真实的", "adj.", "ˈæktʃuəl"],
    ["actually", "实际上", "adv.", "ˈæktʃuəli"],
    ["acute", "敏锐的，严重的", "adj.", "əˈkjuːt"],
    ["adapt", "适应，改编", "v.", "əˈdæpt"],
    ["add", "增加", "v.", "æd"],
    ["addition", "增加，加法", "n.", "əˈdɪʃn"],
    ["additional", "额外的", "adj.", "əˈdɪʃənl"],
    ["address", "地址，演讲", "n./v.", "əˈdres"],
    ["adequate", "充足的", "adj.", "ˈædɪkwət"],
    ["adhere", "坚持，粘附", "v.", "ədˈhɪər"],
    ["adjacent", "毗连的", "adj.", "əˈdʒeɪsnt"],
    ["adjoin", "毗连", "v.", "əˈdʒɔɪn"],
    ["adjust", "调整", "v.", "əˈdʒʌst"],
    ["administer", "管理", "v.", "ədˈmɪnɪstər"],
    ["administration", "管理，行政", "n.", "ədˌmɪnɪˈstreɪʃn"],
    ["admirable", "钦佩的", "adj.", "ˈædmərəbl"],
    ["admire", "钦佩", "v.", "ədˈmaɪər"],
    ["admission", "准许进入", "n.", "ədˈmɪʃn"],
    ["admit", "承认", "v.", "ədˈmɪt"],
    ["adolescent", "青少年", "n.", "ˌædəˈlesnt"],
    ["adopt", "采用，收养", "v.", "əˈdɒpt"],
    ["adore", "崇拜，爱慕", "v.", "əˈdɔːr"],
    ["adult", "成年人", "n.", "ˈædʌlt"],
    ["advance", "前进", "v./n.", "ədˈvɑːns"],
    ["advanced", "先进的", "adj.", "ədˈvɑːnst"],
    ["advantage", "优势", "n.", "ədˈvɑːntɪdʒ"],
    ["adventure", "冒险", "n.", "ədˈventʃər"],
    ["adventurous", "爱冒险的", "adj.", "ədˈventʃərəs"],
    ["adverb", "副词", "n.", "ˈædvɜːrb"],
    ["adverse", "不利的", "adj.", "ˈædvɜːrs"],
    ["advertise", "做广告", "v.", "ˈædvətaɪz"],
    ["advertisement", "广告", "n.", "ədˈvɜːrtɪsmənt"],
    ["advice", "建议", "n.", "ədˈvaɪs"],
    ["advisable", "明智的", "adj.", "ədˈvaɪzəbl"],
    ["advise", "建议", "v.", "ədˈvaɪz"],
    ["advocate", "提倡", "v.", "ˈædvəkeɪt"],
    ["aerial", "航空的，天线", "adj./n.", "ˈeəriəl"],
    ["aeroplane", "飞机", "n.", "ˈeərəpleɪn"],
    ["aesthetic", "美学的", "adj.", "esˈθetɪk"],
    ["affair", "事务", "n.", "əˈfeər"],
    ["affect", "影响", "v.", "əˈfekt"],
    ["affection", "喜爱", "n.", "əˈfekʃn"],
    ["afford", "买得起", "v.", "əˈfɔːrd"],
    ["afraid", "害怕的", "adj.", "əˈfreɪd"],
    ["afterwards", "后来", "adv.", "ˈɑːftəwədz"],
    ["age", "年龄", "n.", "eɪdʒ"],
    ["agency", "代理机构", "n.", "ˈeɪdʒənsi"],
    ["agenda", "议程", "n.", "əˈdʒendə"],
    ["agent", "代理人", "n.", "ˈeɪdʒənt"],
    ["aggressive", "好斗的", "adj.", "əˈɡresɪv"],
    ["agony", "痛苦", "n.", "ˈæɡəni"],
    ["agree", "同意", "v.", "əˈɡriː"],
    ["agreement", "协议", "n.", "əˈɡriːmənt"],
    ["agriculture", "农业", "n.", "ˈæɡrɪkʌltʃər"],
    ["aid", "援助", "v./n.", "eɪd"],
    ["aim", "目标", "v./n.", "eɪm"],
    ["air", "空气", "n.", "eər"],
    ["aircraft", "飞行器", "n.", "ˈeəkrɑːft"],
    ["airline", "航空公司", "n.", "ˈeəlaɪn"],
    ["airplane", "飞机", "n.", "ˈeəpleɪn"],
    ["airport", "机场", "n.", "ˈeəpɔːrt"],
    ["alarm", "警报", "n.", "əˈlɑːm"],
    ["alcohol", "酒精", "n.", "ˈælkəhɒl"],
    ["alert", "警觉的", "adj.", "əˈlɜːrt"],
    ["alien", "外星人", "n.", "ˈeɪliən"],
    ["alike", "相似的", "adj.", "əˈlaɪk"],
    ["alive", "活着的", "adj.", "əˈlaɪv"],
    ["all", "所有的", "adj.", "ɔːl"],
    ["allege", "声称", "v.", "əˈledʒ"],
    ["alleviate", "减轻", "v.", "əˈliːvieɪt"],
    ["alliance", "联盟", "n.", "əˈlaɪəns"],
    ["allocate", "分配", "v.", "ˈæləkeɪt"],
    ["allow", "允许", "v.", "əˈlaʊ"],
    ["allowance", "津贴", "n.", "əˈlaʊəns"],
    ["alloy", "合金", "n.", "ˈælɔɪ"],
    ["almost", "几乎", "adv.", "ˈɔːlməʊst"],
    ["alone", "单独的", "adj.", "əˈləʊn"],
    ["alongside", "在...旁边", "adv.", "əˌlɒŋˈsaɪd"],
    ["aloud", "大声地", "adv.", "əˈlaʊd"],
    ["alphabet", "字母表", "n.", "ˈælfəbet"],
    ["alter", "改变", "v.", "ˈɔːltər"],
    ["alternative", "选择", "n.", "ɔːlˈtɜːrnətɪv"],
    ["although", "虽然", "conj.", "ɔːlˈðəʊ"],
    ["altitude", "高度", "n.", "ˈæltɪtjuːd"],
    ["altogether", "完全", "adv.", "ˌɔːltəˈɡeðər"],
    ["aluminum", "铝", "n.", "əˈluːmɪnəm"],
    ["amaze", "大吃一惊", "v.", "əˈmeɪz"],
    ["ambassador", "大使", "n.", "æmˈbæsədər"],
    ["ambiguous", "模糊的", "adj.", "æmˈbɪɡjuəs"],
    ["ambition", "雄心", "n.", "æmˈbɪʃn"],
    ["ambitious", "有雄心的", "adj.", "æmˈbɪʃəs"],
    ["ambulance", "救护车", "n.", "ˈæmbjələns"],
    ["amend", "修改", "v.", "əˈmend"],
    ["amendment", "修正案", "n.", "əˈmendmənt"],
    ["amiable", "和蔼的", "adj.", "ˈeɪmiəbl"],
    ["amid", "在...中间", "prep.", "əˈmɪd"],
    ["amount", "金额，数量", "n.", "əˈmaʊnt"],
    ["ample", "宽敞的", "adj.", "ˈæmpl"],
    ["amplify", "放大", "v.", "ˈæmplɪfaɪ"],
    ["amuse", "娱乐", "v.", "əˈmjuːz"],
    ["amusement", "娱乐", "n.", "əˈmjuːzmənt"],
    ["analogy", "类比", "n.", "əˈnælədʒi"],
    ["analyse", "分析", "v.", "ˈænəlaɪz"],
    ["analysis", "分析", "n.", "əˈnæləsɪs"],
    ["ancestor", "祖先", "n.", "ˈænsestər"],
    ["anchor", "锚", "n.", "ˈæŋkər"],
    ["ancient", "古代的", "adj.", "ˈeɪnʃənt"],
    ["and", "和", "conj.", "ænd"],
    ["angel", "天使", "n.", "ˈeɪndʒl"],
    ["anger", "愤怒", "n.", "ˈæŋɡər"],
    ["angle", "角度", "n.", "ˈæŋɡl"],
    ["angry", "生气", "adj.", "ˈæŋɡri"],
    ["animal", "动物", "n.", "ˈænɪml"],
    ["ankle", "脚踝", "n.", "ˈæŋkl"],
    ["anniversary", "周年纪念", "n.", "ˌænɪˈvɜːrsəri"],
    ["announce", "宣布", "v.", "əˈnaʊns"],
    ["announcement", "通知", "n.", "əˈnaʊnsmənt"],
    ["annoy", "使苦恼", "v.", "əˈnɔɪ"],
    ["annual", "每年的", "adj.", "ˈænjuəl"],
    ["anonymous", "匿名的", "adj.", "əˈnɒnɪməs"],
    ["another", "另一个", "adj.", "əˈnʌðər"],
    ["answer", "回答", "v./n.", "ˈɑːnsər"],
    ["ant", "蚂蚁", "n.", "ænt"],
    ["antarctic", "南极的", "adj.", "ænˈtɑːrktɪk"],
    ["antenna", "天线", "n.", "ænˈtenə"],
    ["anticipate", "预期", "v.", "ænˈtɪsɪpeɪt"],
    ["antique", "古董", "n.", "ænˈtiːk"],
    ["anxiety", "焦虑", "n.", "æŋˈzaɪəti"],
    ["anxious", "焦虑的", "adj.", "ˈæŋkʃəs"],
    ["any", "任何", "adj.", "ˈeni"],
    ["anybody", "任何人", "pron.", "ˈenibɒdi"],
    ["anyhow", "不管怎样", "adv.", "ˈenihaʊ"],
    ["anyone", "任何人", "pron.", "ˈeniwʌn"],
    ["anything", "任何事", "pron.", "ˈeniθɪŋ"],
    ["anyway", "无论如何", "adv.", "ˈeniweɪ"],
    ["anywhere", "任何地方", "adv.", "ˈeniweər"],
    ["apart", "分开", "adv.", "əˈpɑːrt"],
    ["apartment", "公寓", "n.", "əˈpɑːrtmənt"],
    ["apologise", "道歉", "v.", "əˈpɒlədʒaɪz"],
    ["apology", "道歉", "n.", "əˈpɒlədʒi"],
    ["apparatus", "装置", "n.", "ˌæpəˈreɪtəs"],
    ["apparent", "明显的", "adj.", "əˈpærənt"],
    ["appeal", "呼吁", "v./n.", "əˈpiːl"],
    ["appear", "出现", "v.", "əˈpɪər"],
    ["appearance", "外观", "n.", "əˈpɪərəns"],
    ["appendix", "附录", "n.", "əˈpendɪks"],
    ["appetite", "胃口", "n.", "ˈæpɪtaɪt"],
    ["applaud", "鼓掌", "v.", "əˈplɔːd"],
    ["applause", "掌声", "n.", "əˈplɔːz"],
    ["apple", "苹果", "n.", "ˈæpl"],
    ["appliance", "电器", "n.", "əˈplaɪəns"],
    ["applicable", "适用的", "adj.", "əˈplɪkəbl"],
    ["application", "申请", "n.", "ˌæplɪˈkeɪʃn"],
    ["apply", "应用", "v.", "əˈplaɪ"],
    ["appoint", "任命", "v.", "əˈpɔɪnt"],
    ["appointment", "约定", "n.", "əˈpɔɪntmənt"],
    ["appraisal", "评估", "n.", "əˈpreɪzl"],
    ["appreciate", "欣赏", "v.", "əˈpriːʃieɪt"],
    ["appreciation", "感激", "n.", "əˌpriːʃiˈeɪʃn"],
    ["approach", "接近", "v.", "əˈprəʊtʃ"],
    ["appropriate", "适当的", "adj.", "əˈprəʊpriət"],
    ["approval", "赞成", "n.", "əˈpruːvl"],
    ["approve", "批准", "v.", "əˈpruːv"],
    ["approximate", "大概的", "adj.", "əˈprɒksɪmət"],
    ["apron", "围裙", "n.", "ˈeɪprən"],
    ["apt", "恰当的", "adj.", "æpt"],
    ["arbitrary", "随意的", "adj.", "ˈɑːrbɪtreri"],
    ["arch", "拱门", "n.", "ɑːrtʃ"],
    ["architecture", "建筑", "n.", "ˈɑːrkɪtektʃər"],
    ["arctic", "北极的", "adj.", "ˈɑːrktɪk"],
    ["area", "区域", "n.", "ˈeəriə"],
    ["argue", "争论", "v.", "ˈɑːɡjuː"],
    ["argument", "争论", "n.", "ˈɑːɡjumənt"],
    ["arise", "出现", "v.", "əˈraɪz"],
    ["arithmetic", "算数", "n.", "əˈrɪθmətɪk"],
    ["arm", "手臂", "n.", "ɑːrm"],
    ["army", "军队", "n.", "ˈɑːrmi"],
    ["around", "在...周围", "prep.", "əˈraʊnd"],
    ["arouse", "激发", "v.", "əˈraʊz"],
    ["arrange", "安排", "v.", "əˈreɪndʒ"],
    ["arrangement", "安排", "n.", "əˈreɪndʒmənt"],
    ["array", "陈列", "n.", "əˈreɪ"],
    ["arrest", "逮捕", "v./n.", "əˈrest"],
    ["arrival", "到达", "n.", "əˈraɪvl"],
    ["arrive", "到达", "v.", "əˈraɪv"],
    ["arrogant", "傲慢的", "adj.", "ˈærəɡənt"],
    ["arrow", "箭", "n.", "ˈærəʊ"],
    ["art", "艺术", "n.", "ɑːrt"],
    ["artery", "动脉", "n.", "ˈɑːrtəri"],
    ["article", "文章", "n.", "ˈɑːrtɪkl"],
    ["articulate", "善于表达", "adj.", "ɑːrˈtɪkjulət"],
    ["artificial", "人造的", "adj.", "ˌɑːrtɪˈfɪʃl"],
    ["artillery", "大炮", "n.", "ɑːrˈtɪləri"],
    ["artist", "艺术家", "n.", "ˈɑːrtɪst"],
    ["artistic", "艺术的", "adj.", "ɑːrˈtɪstɪk"],
    ["as", "作为", "prep.", "æz"],
    ["ascend", "上升", "v.", "əˈsend"],
    ["ascertain", "查明", "v.", "ˌæsərˈteɪn"],
    ["ash", "灰烬", "n.", "æʃ"],
    ["ashamed", "羞愧的", "adj.", "əˈʃeɪmd"],
    ["aside", "在旁边", "adv.", "əˈsaɪd"],
    ["ask", "问", "v.", "ɑːsk"],
    ["asleep", "睡着的", "adj.", "əˈsliːp"],
    ["aspect", "方面", "n.", "ˈæspekt"],
    ["aspire", "渴望", "v.", "əˈspaɪər"],
    ["assassin", "刺客", "n.", "əˈsæsɪn"],
    ["assassinate", "暗杀", "v.", "əˈsæsɪneɪt"],
    ["assault", "攻击", "v./n.", "əˈsɔːlt"],
    ["assemble", "集合", "v.", "əˈsembl"],
    ["assembly", "集会", "n.", "əˈsembli"],
    ["assert", "断言", "v.", "əˈsɜːrt"],
    ["assess", "评估", "v.", "əˈses"],
    ["assessment", "评价", "n.", "əˈsesmənt"],
    ["asset", "资产", "n.", "ˈæset"],
    ["assign", "分配", "v.", "əˈsaɪn"],
    ["assignment", "作业", "n.", "əˈsaɪnmənt"],
    ["assimilate", "吸收", "v.", "əˈsɪməleɪt"],
    ["assist", "协助", "v.", "əˈsɪst"],
    ["assistance", "协助", "n.", "əˈsɪstəns"],
    ["assistant", "助手", "n.", "əˈsɪstənt"],
    ["associate", "联系", "v.", "əˈsəʊʃieɪt"],
    ["association", "协会", "n.", "əˌsəʊʃiˈeɪʃn"],
    ["assume", "假设", "v.", "əˈsjuːm"],
    ["assumption", "假定", "n.", "əˈsʌmpʃn"],
    ["assurance", "保证", "n.", "əˈʃʊərəns"],
    ["assure", "向...保证", "v.", "əˈʃʊər"],
    ["astonish", "使...惊讶", "v.", "əˈstɒnɪʃ"],
    ["astronaut", "宇航员", "n.", "ˈæstrənɔːt"],
    ["astronomy", "天文学", "n.", "əˈstrɒnəmi"],
    ["at", "在", "prep.", "æt"],
    ["athlete", "运动员", "n.", "ˈæθliːt"],
    ["atmosphere", "大气", "n.", "ˈætməsfɪər"],
    ["atom", "原子", "n.", "ˈætəm"],
    ["atomic", "原子的", "adj.", "əˈtɒmɪk"],
    ["attach", "附属", "v.", "əˈtætʃ"],
    ["attachment", "附件", "n.", "əˈtætʃmənt"],
    ["attack", "攻击", "v./n.", "əˈtæk"],
    ["attain", "获得", "v.", "əˈteɪn"],
    ["attempt", "尝试", "v./n.", "əˈtempt"],
    ["attend", "参加", "v.", "əˈtend"],
    ["attendance", "出席人数", "n.", "əˈtendəns"],
    ["attention", "注意", "n.", "əˈtenʃn"],
    ["attentive", "细心的", "adj.", "əˈtentɪv"],
    ["attitude", "态度", "n.", "ˈætɪtjuːd"],
    ["attorney", "律师", "n.", "əˈtɜːrni"],
    ["attract", "吸引", "v.", "əˈtrækt"],
    ["attraction", "吸引力", "n.", "əˈtrækʃn"],
    ["attractive", "有吸引力的", "adj.", "əˈtræktɪv"],
    ["attribute", "归咎于", "v.", "əˈtrɪbjuːt"],
    ["auction", "拍卖", "n.", "ˈɔːkʃn"],
    ["audience", "观众", "n.", "ˈɔːdiəns"],
    ["audio", "音频", "n.", "ˈɔːdiəʊ"],
    ["audit", "审计", "v.", "ˈɔːdɪt"],
    ["auditorium", "礼堂", "n.", "ˌɔːdɪˈtɔːriəm"],
    ["august", "八月", "n.", "ˈɔːɡəst"],
    ["aunt", "姨母", "n.", "ɑːnt"],
    ["authentic", "真实的", "adj.", "ɔːˈθentɪk"],
    ["author", "作者", "n.", "ˈɔːθər"],
    ["authority", "权威", "n.", "əˈθɒrəti"],
    ["authorize", "授权", "v.", "ˈɔːθəraɪz"]
];

function generateLevels() {
    const levels = [];
    const baseId = 11;
    for (let i = 0; i < 30; i++) {
        const startIndex = i * 10;
        const levelWords = wordsRaw.slice(startIndex, startIndex + 10);
        if (levelWords.length === 0) break;

        const islandNames = [
            "蔚蓝海湾", "珊瑚礁群", "落日余晖", "极地冰封", "幽暗深渊", 
            "梦幻海港", "群星圣殿", "永恒森林", "烈焰山脉", "雷鸣峡谷",
            "翡翠草原", "黄金沙漠", "琥珀盆地", "银色沙滩", "迷雾山峰",
            "水晶洞穴", "彩虹群岛", "风暴之眼", "幽灵船墓", "生命之泉",
            "机械堡垒", "时光隧道", "远古遗迹", "天空之城", "暗影迷宫",
            "奇迹广场", "英雄丰碑", "智慧殿堂", "真理彼岸", "终焉之地"
        ];

        const wordsObjects = levelWords.map(w => ({
            word: w[0],
            meaning: w[1],
            pos: w[2],
            phonetic: w[3]
        }));

        const storyWords = wordsObjects.map(w => `[${w.word}]`).join(', ');

        levels.push({
            id: baseId + i,
            name: islandNames[i] || `神秘岛屿 ${baseId + i}`,
            storyTitle: `Richard：新的航程 第${baseId + i}章`,
            storySegment: `Richard继续他的探险，来到了【${islandNames[i] || `神秘岛屿 ${baseId + i}`}】。他不断学习新的词汇：${levelWords.map(w => w[0]).slice(0, 3).join('、')}等。`,
            storyPassage: `Richard explored the ${islandNames[i] || `Island ${baseId + i}`}. He found many interesting things. He used his knowledge of ${storyWords} to understand the surroundings and move forward. Each word was like a key to a new mystery.`,
            storyEnding: `Richard successfully mastered the words of ${islandNames[i] || `Island ${baseId + i}`} and is ready for the next challenge!`,
            words: wordsObjects
        });
    }
    return levels;
}

const newLevels = generateLevels();
console.log(JSON.stringify(newLevels, null, 2));

